"""Base Planejamento 1.2

Revision ID: 029cd86b199c
Revises: ac4cc69ad12e
Create Date: 2023-06-19 18:29:47.746925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '029cd86b199c'
down_revision = 'ac4cc69ad12e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts_instagram', schema=None) as batch_op:
        batch_op.alter_column('caption',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=2000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts_instagram', schema=None) as batch_op:
        batch_op.alter_column('caption',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)

    # ### end Alembic commands ###
