"""added subtarefas

Revision ID: 0811751b1fc6
Revises: 64385a441b34
Create Date: 2023-08-17 17:15:58.080317

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0811751b1fc6'
down_revision = '64385a441b34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ads')
    op.drop_table('tarefas_concluidas')
    with op.batch_alter_table('seguidores', schema=None) as batch_op:
        batch_op.drop_index('ix_seguidores_id_empresa')

    op.drop_table('seguidores')
    op.drop_table('tarefas_atuais')
    with op.batch_alter_table('tarefas_andamento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtarefas', sa.JSON(), nullable=True))

    with op.batch_alter_table('tarefas_finalizadas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtarefas', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tarefas_finalizadas', schema=None) as batch_op:
        batch_op.drop_column('subtarefas')

    with op.batch_alter_table('tarefas_andamento', schema=None) as batch_op:
        batch_op.drop_column('subtarefas')

    op.create_table('tarefas_atuais',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('empresa', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('squad_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('squad_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tarefa', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('data_inclusao', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('data_conclusao', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['squad_id'], ['squad.id'], name='tarefas_atuais_squad_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='tarefas_atuais_pkey')
    )
    op.create_table('seguidores',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_empresa', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('data_criacao', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('nome_empresa', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('seguidores', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='seguidores_pkey')
    )
    with op.batch_alter_table('seguidores', schema=None) as batch_op:
        batch_op.create_index('ix_seguidores_id_empresa', ['id_empresa'], unique=False)

    op.create_table('tarefas_concluidas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('empresa', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('squad_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('squad_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tarefa', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('data_inclusao', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('data_conclusao', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['squad_id'], ['squad.id'], name='tarefas_concluidas_squad_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='tarefas_concluidas_pkey')
    )
    op.create_table('ads',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_empresa', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timestamp', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('nome_grupo', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('nome_campanha', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('nome_anuncio', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('valor', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('impressoes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('landing', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cpm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ctr', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('cpc', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('nome_empresa', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresa.id'], name='ads_id_empresa_fkey'),
    sa.PrimaryKeyConstraint('id', name='ads_pkey')
    )
    # ### end Alembic commands ###
