"""Mudança class Analise Instagram

Revision ID: 1786db8ae12c
Revises: dfdc1e2fe539
Create Date: 2023-07-05 18:00:27.343833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1786db8ae12c'
down_revision = 'dfdc1e2fe539'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analise_instagram', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recente', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analise_instagram', schema=None) as batch_op:
        batch_op.drop_column('recente')

    # ### end Alembic commands ###
