"""mudança class MacroAcao mudança squad_id

Revision ID: 3621fc4aeb15
Revises: 307a020a954a
Create Date: 2023-08-07 14:52:06.044326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3621fc4aeb15'
down_revision = '307a020a954a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('macro_acao', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'squad', ['squad_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('macro_acao', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
