"""Mudança class PostInstagram

Revision ID: 44328b06a715
Revises: b41fd099af7c
Create Date: 2023-07-03 12:10:04.070138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44328b06a715'
down_revision = 'b41fd099af7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts_instagram', schema=None) as batch_op:
        batch_op.add_column(sa.Column('analisado', sa.Boolean(), nullable=True))
        batch_op.alter_column('caption',
               existing_type=sa.VARCHAR(length=2000),
               type_=sa.String(length=64),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts_instagram', schema=None) as batch_op:
        batch_op.alter_column('caption',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=2000),
               existing_nullable=True)
        batch_op.drop_column('analisado')

    # ### end Alembic commands ###
