"""Alteração na TarefaSemanal

Revision ID: 5881d8b607bb
Revises: e3ff8b32e03f
Create Date: 2023-06-06 11:10:20.688439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5881d8b607bb'
down_revision = 'e3ff8b32e03f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tarefa_semanal', schema=None) as batch_op:
        batch_op.alter_column('to_do',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=10000),
               existing_nullable=True)
        batch_op.alter_column('observacoes',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=10000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tarefa_semanal', schema=None) as batch_op:
        batch_op.alter_column('observacoes',
               existing_type=sa.String(length=10000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('to_do',
               existing_type=sa.String(length=10000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###
