"""Campo vincular_anuncio = db.Column(db.String(200)) em empresa

Revision ID: 59ab5cccfece
Revises: fbf65f32ab6d
Create Date: 2023-06-28 15:52:26.803001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59ab5cccfece'
down_revision = 'fbf65f32ab6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vincular_anuncio', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.drop_column('vincular_anuncio')

    # ### end Alembic commands ###
