"""class anuncios

Revision ID: 5ffaf5c41999
Revises: bd64d3e0878a
Create Date: 2023-07-26 18:13:54.461783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ffaf5c41999'
down_revision = 'bd64d3e0878a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anuncios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('impressoes', sa.Integer(), nullable=True),
    sa.Column('landing', sa.Integer(), nullable=True),
    sa.Column('cpm', sa.Float(), nullable=True),
    sa.Column('ctr', sa.Float(), nullable=True),
    sa.Column('cpc', sa.Float(), nullable=True),
    sa.Column('nome_empresa', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anuncios')
    # ### end Alembic commands ###
