"""mudanaça class TarefasAtuais e TarefasConcluidas 2

Revision ID: 64385a441b34
Revises: ce869000b049
Create Date: 2023-08-09 15:19:10.269849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64385a441b34'
down_revision = 'ce869000b049'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tarefas_atuais', schema=None) as batch_op:
        batch_op.drop_constraint('tarefas_atuais_kr_id_fkey', type_='foreignkey')
        batch_op.drop_column('kr_id')

    with op.batch_alter_table('tarefas_concluidas', schema=None) as batch_op:
        batch_op.drop_constraint('tarefas_concluidas_kr_id_fkey', type_='foreignkey')
        batch_op.drop_column('kr_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tarefas_concluidas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kr_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('tarefas_concluidas_kr_id_fkey', 'kr', ['kr_id'], ['id'])

    with op.batch_alter_table('tarefas_atuais', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kr_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('tarefas_atuais_kr_id_fkey', 'kr', ['kr_id'], ['id'])

    # ### end Alembic commands ###
