"""Alteração na TarefaSemanal

Revision ID: a6c1771d51cc
Revises: 5881d8b607bb
Create Date: 2023-06-15 16:05:14.019901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6c1771d51cc'
down_revision = '5881d8b607bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vincular_instagram', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.drop_column('vincular_instagram')

    # ### end Alembic commands ###
