"""inclusao de class kr temporario

Revision ID: cef45ef8be2a
Revises: b138c5c476a5
Create Date: 2023-08-02 13:56:58.799461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cef45ef8be2a'
down_revision = 'b138c5c476a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kr_gerado_chat_aprovacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('objetivo', sa.String(length=255), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('squad_id', sa.Integer(), nullable=False),
    sa.Column('KR', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['squad_id'], ['squad.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kr_gerado_chat_aprovacao')
    # ### end Alembic commands ###
