"""Mudança na class Post Intagram 1

Revision ID: dfdc1e2fe539
Revises: 44328b06a715
Create Date: 2023-07-03 13:50:14.324260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfdc1e2fe539'
down_revision = '44328b06a715'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts_instagram', schema=None) as batch_op:
        batch_op.add_column(sa.Column('analisado', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts_instagram', schema=None) as batch_op:
        batch_op.drop_column('analisado')

    # ### end Alembic commands ###
