"""base kr 1

Revision ID: e3ff8b32e03f
Revises: ba872004bf2e
Create Date: 2023-05-22 20:10:32.822116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3ff8b32e03f'
down_revision = 'ba872004bf2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kr', schema=None) as batch_op:
        batch_op.add_column(sa.Column('objetivo_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('empresa_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'okr', ['objetivo_id'], ['id'])
        batch_op.create_foreign_key(None, 'empresa', ['empresa_id'], ['id'])
        batch_op.drop_column('id_okr')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kr', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_okr', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'okr', ['id_okr'], ['id'])
        batch_op.drop_column('empresa_id')
        batch_op.drop_column('objetivo_id')

    # ### end Alembic commands ###
