"""Base Planejamento

Revision ID: ea55f02882c1
Revises: a6c1771d51cc
Create Date: 2023-06-15 16:47:55.523321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea55f02882c1'
down_revision = 'a6c1771d51cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vincular_instagram', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.drop_column('vincular_instagram')

    # ### end Alembic commands ###
