"""Campo dado_1_sprint na class Sprint

Revision ID: fbf65f32ab6d
Revises: 029cd86b199c
Create Date: 2023-06-26 17:19:50.244570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbf65f32ab6d'
down_revision = '029cd86b199c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sprint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dado_1_sprint', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sprint', schema=None) as batch_op:
        batch_op.drop_column('dado_1_sprint')

    # ### end Alembic commands ###
